variables:
  DOCKER_REG: dk.jingli365.com
  DOCKER_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  DOCKER_CI_NAME: $DOCKER_REG/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_BUILD_REF
  DOCKER_BRANCH_NAME: $DOCKER_REG/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_BUILD_REF_SLUG
  NPM_CACHE_DIR: /cache/build-cache/npmhash/
  JL_APP_DAEMON: "true"
  JL_APP_COMMAND: node server.js >/data/log/nohup.out 2>&1
  JL_APP_DAEMON_WAIT_INIT: log/nohup.out
  JL_APP_PORT: 8080
  JL_APP_JUHE_KEY: "58db4718504b1fa7a7448a8024c41864"

stages:
  - build
  - docker
  - deploy

image: docker:git

before_script:
  - 'eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY">.k && chmod 600 .k && ssh-add .k && rm -f .k'
  - 'mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\tSendEnv JL_APP_*\n\n" > ~/.ssh/config'
  - mkdir -p /cache/build-cache/.npm && ln -s /cache/build-cache/.npm ~/

build:dist:
  stage: build
  only:
    - branches
  image: $DOCKER_REG/jl-build:v3
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - dist/
  script:
    # - --mkdir -p $NPM_CACHE_DIR/`npmhash`/node_modules && ln -s $NPM_CACHE_DIR/`npmhash`/node_modules .
    # - --echo `npmhash`
    - git submodule update --init --checkout
    - npm install
    - gulp dist
    - ls dist/http/ -al

build:image:
  stage: docker
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - dist/
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker build -t $DOCKER_CI_NAME . --build-arg NPM_TOKEN=$NPM_TOKEN
    - docker push $DOCKER_CI_NAME

deploy:master:
  stage: deploy
  only:
    - /^master$/
  environment:
    name: dev
    url: https://l.jingli365.com/proj/svr-jlbudget/
  variables:
    JL_APP_HOST: http://l.jingli365.com/proj/svr-jlbudget
    JL_APP_POSTGRES: postgres://times:time0418@l.jingli365.com:15432/jlbudget
    JL_APP_OLD_POSTGRES_URL: postgres://times:time0418@l.jingli365.com:15432/times
    JL_APP_REDIS: redis://l.jingli365.com:16379
    JL_APP_DATA_STORE_URL: https://l.jingli365.com/proj/svr-data-store
    JL_APP_PLACE: https://l.jingli365.com/proj/svr-place
    JL_APP_COMMONAPI_HOST: l.jingli365.com
    JL_APP_COMMONAPI_PORT: 14101
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://l.jingli365.com
    - ssh test@l.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_BUILD_REF_SLUG -p 8080 -p 14103:4103

deploy:test:
  stage: deploy
  only:
    - /^test$/
  environment:
    name: test
    url: https://t.jingli365.com/proj/svr-jlbudget/
  variables:
    JL_APP_HOST: https://t.jingli365.com/proj/svr-jlbudget
    JL_APP_POSTGRES: postgres://times:time0418@t.jingli365.com:15432/t_jlbudget
    JL_APP_OLD_POSTGRES_URL: postgres://times:time0418@t.jingli365.com:15432/times
    JL_APP_REDIS: redis://t.jingli365.com:16379
    JL_APP_DATA_STORE_URL: https://t.jingli365.com/proj/svr-data-store
    JL_APP_PLACE: https://t.jingli365.com/proj/svr-place
    JL_APP_COMMONAPI_HOST: t.jingli365.com
    JL_APP_COMMONAPI_PORT: 14201
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://t.jingli365.com
    - ssh test@t.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_BUILD_REF_SLUG -p 8080 -p 14113:4103

deploy:tester:
  stage: deploy
  when: manual
  environment:
    name: tester/$GITLAB_USER_ID
    url: https://review.l.jingli365.com/vm/$GITLAB_USER_ID/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  variables:
    JL_APP_HOST: //review.l.jingli365.com/tester/$GITLAB_USER_ID/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
    JL_APP_REDIS: redis://l.jingli365.com:16379
    JL_APP_POSTGRES: postgres://test:JingliTest0418@dockerhost:15432/budget_tester_$GITLAB_USER_ID
    JL_APP_POSTGRES_INITDB: tester_$GITLAB_USER_ID
    JL_APP_OLD_POSTGRES_URL: postgres://times:time0418@l.jingli365.com:15432/times
    JL_APP_DATA_STORE_URL: https://l.jingli365.com/proj/svr-data-store
    JL_APP_PLACE: https://l.jingli365.com/proj/svr-place
    JL_APP_COMMONAPI_HOST: t.jingli365.com
    JL_APP_COMMONAPI_PORT: 14201
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_REG/$DOCKER_NAME:tester-$GITLAB_USER_ID
    - docker push $DOCKER_REG/$DOCKER_NAME:tester-$GITLAB_USER_ID
    - echo deploy to https://review.l.jingli365.com/tester/$GITLAB_USER_ID
    - ssh test@l.jingli365.com /home/test/bin/docker_start.sh $DOCKER_REG $DOCKER_NAME tester-$GITLAB_USER_ID -p 8080

  after_script:
    - 'npm test 2&>1'


deploy:release:
  stage: deploy
  only:
    - /^release$/
  when: manual
  environment:
    name: release
    url: https://budget.jingli365.com
  variables:
    JL_APP_HOST: "https://j.jingli365.com/proj/svr-jlbudget"
    JL_APP_COMMONAPI_HOST: j.jingli365.com
    JL_APP_COMMONAPI_PORT: 4201
    JL_APP_DATA_STORE: j.jingli365.com
    JL_APP_DATA_STORE_PORT: 4106
    JL_APP_DATA_STORE_URL: https://j.jingli365.com/proj/svr-data-store
    JL_APP_REDIS: redis://j.jingli365.com
    JL_APP_PLACE: https://j.jingli365.com/proj/svr-place
    JL_APP_POSTGRES: postgres://jingli:J1n9L1.t3ch@j.jingli365.com:5432/jlbudget
    JL_APP_OLD_POSTGRES_URL: postgres://jingli:J1n9L1.t3ch@j.jingli365.com:5432/qmtrip
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://budget.jingli365.com
    - ssh test@j.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_BUILD_REF_SLUG -p 8080 -p 4103:4103


deploy:demo:
  stage: deploy
  only:
    - /^demo$/
  when: manual
  environment:
    name: demo
    url: https://demo.jingli365.com/proj/svr-jlbudget/
  variables:
    JL_APP_HOST: "http://demo.jingli365.com/proj/svr-jlbudget"
    JL_APP_COMMONAPI_HOST: demo.jingli365.com
    JL_APP_COMMONAPI_PORT: 4201
    JL_APP_DATA_STORE: j.jingli365.com
    JL_APP_DATA_STORE_PORT: 4106
    JL_APP_DATA_STORE_URL: https://j.jingli365.com/proj/svr-data-store
    JL_APP_REDIS: redis://demo.jingli365.com
    JL_APP_PLACE: https://j.jingli365.com/proj/svr-place
    JL_APP_POSTGRES: postgres://jingli:J1n9L1.t3ch@demo.jingli365.com:5432/jlbudget-demo
    JL_APP_OLD_POSTGRES_URL: postgres://jingli:J1n9L1.t3ch@demo.jingli365.com:5432/qmtrip-demo
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://demo.jingli365.com
    - ssh test@demo.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_BUILD_REF_SLUG -p 8080 -p 24103:4103
